// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBookmark(arg1) {
  return window['go']['main']['App']['AddBookmark'](arg1);
}

export function AddSearchHistory(arg1) {
  return window['go']['main']['App']['AddSearchHistory'](arg1);
}

export function AddToCollection(arg1) {
  return window['go']['main']['App']['AddToCollection'](arg1);
}

export function ClearDownloadHistory() {
  return window['go']['main']['App']['ClearDownloadHistory']();
}

export function ClearSearchHistory() {
  return window['go']['main']['App']['ClearSearchHistory']();
}

export function CountAudioFiles(arg1) {
  return window['go']['main']['App']['CountAudioFiles'](arg1);
}

export function DownloadFiles(arg1, arg2) {
  return window['go']['main']['App']['DownloadFiles'](arg1, arg2);
}

export function DownloadSingle(arg1) {
  return window['go']['main']['App']['DownloadSingle'](arg1);
}

export function GetAlbum(arg1) {
  return window['go']['main']['App']['GetAlbum'](arg1);
}

export function GetAlbumDownloadedTracks(arg1) {
  return window['go']['main']['App']['GetAlbumDownloadedTracks'](arg1);
}

export function GetBaseURL() {
  return window['go']['main']['App']['GetBaseURL']();
}

export function GetBookmarks() {
  return window['go']['main']['App']['GetBookmarks']();
}

export function GetCollection() {
  return window['go']['main']['App']['GetCollection']();
}

export function GetDownloadHistory() {
  return window['go']['main']['App']['GetDownloadHistory']();
}

export function GetFolder() {
  return window['go']['main']['App']['GetFolder']();
}

export function GetLibraryFolder() {
  return window['go']['main']['App']['GetLibraryFolder']();
}

export function GetSearchHistory() {
  return window['go']['main']['App']['GetSearchHistory']();
}

export function IgnoreLibraryFolder(arg1) {
  return window['go']['main']['App']['IgnoreLibraryFolder'](arg1);
}

export function IsBookmarked(arg1) {
  return window['go']['main']['App']['IsBookmarked'](arg1);
}

export function IsInCollection(arg1) {
  return window['go']['main']['App']['IsInCollection'](arg1);
}

export function RecordAlbumDownload(arg1) {
  return window['go']['main']['App']['RecordAlbumDownload'](arg1);
}

export function RemoveBookmark(arg1) {
  return window['go']['main']['App']['RemoveBookmark'](arg1);
}

export function RemoveCollectionEntry(arg1) {
  return window['go']['main']['App']['RemoveCollectionEntry'](arg1);
}

export function RemoveFromCollection(arg1) {
  return window['go']['main']['App']['RemoveFromCollection'](arg1);
}

export function ResolveCollectionMatch(arg1, arg2) {
  return window['go']['main']['App']['ResolveCollectionMatch'](arg1, arg2);
}

export function ScanLibrary() {
  return window['go']['main']['App']['ScanLibrary']();
}

export function SearchAlbums(arg1) {
  return window['go']['main']['App']['SearchAlbums'](arg1);
}

export function SelectAlbumFolder() {
  return window['go']['main']['App']['SelectAlbumFolder']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectLibraryFolder() {
  return window['go']['main']['App']['SelectLibraryFolder']();
}

export function SetBaseURL(arg1) {
  return window['go']['main']['App']['SetBaseURL'](arg1);
}

export function TrackFilename(arg1) {
  return window['go']['main']['App']['TrackFilename'](arg1);
}
