// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddBookmark(arg1:main.BookmarkedAlbum):Promise<void>;

export function AddSearchHistory(arg1:string):Promise<Array<main.SearchHistoryItem>>;

export function ClearDownloadHistory():Promise<void>;

export function ClearSearchHistory():Promise<void>;

export function DownloadFiles(arg1:string,arg2:Array<string>):Promise<void>;

export function DownloadSingle(arg1:string):Promise<void>;

export function GetAlbum(arg1:string):Promise<main.ApiResponse_main_AlbumData_>;

export function GetAlbumDownloadedTracks(arg1:string):Promise<Array<string>>;

export function GetBaseURL():Promise<string>;

export function GetBookmarks():Promise<Array<main.BookmarkedAlbum>>;

export function GetDownloadHistory():Promise<Array<main.DownloadedAlbum>>;

export function GetFolder():Promise<string>;

export function GetSearchHistory():Promise<Array<main.SearchHistoryItem>>;

export function IsBookmarked(arg1:string):Promise<boolean>;

export function RecordAlbumDownload(arg1:main.DownloadedAlbum):Promise<void>;

export function RemoveBookmark(arg1:string):Promise<void>;

export function SearchAlbums(arg1:string):Promise<main.ApiResponse___main_Album_>;

export function SelectFolder():Promise<string>;

export function SetBaseURL(arg1:string):Promise<void>;
