// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSearchHistory(arg1) {
  return window['go']['main']['App']['AddSearchHistory'](arg1);
}

export function ClearDownloadHistory() {
  return window['go']['main']['App']['ClearDownloadHistory']();
}

export function ClearSearchHistory() {
  return window['go']['main']['App']['ClearSearchHistory']();
}

export function DownloadFiles(arg1, arg2) {
  return window['go']['main']['App']['DownloadFiles'](arg1, arg2);
}

export function DownloadSingle(arg1) {
  return window['go']['main']['App']['DownloadSingle'](arg1);
}

export function GetAlbum(arg1) {
  return window['go']['main']['App']['GetAlbum'](arg1);
}

export function GetAlbumDownloadedTracks(arg1) {
  return window['go']['main']['App']['GetAlbumDownloadedTracks'](arg1);
}

export function GetBaseURL() {
  return window['go']['main']['App']['GetBaseURL']();
}

export function GetDownloadHistory() {
  return window['go']['main']['App']['GetDownloadHistory']();
}

export function GetFolder() {
  return window['go']['main']['App']['GetFolder']();
}

export function GetSearchHistory() {
  return window['go']['main']['App']['GetSearchHistory']();
}

export function RecordAlbumDownload(arg1) {
  return window['go']['main']['App']['RecordAlbumDownload'](arg1);
}

export function SearchAlbums(arg1) {
  return window['go']['main']['App']['SearchAlbums'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetBaseURL(arg1) {
  return window['go']['main']['App']['SetBaseURL'](arg1);
}
